version: '2.1'
services:
  jobmanager:
    image: flink:1.11.0-scala_2.11
    volumes:
      - ./tasks:/opt/tasks
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: flink:1.11.0-scala_2.11
    volumes:
      - ./tasks:/opt/tasks
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 6
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  canal-server:
    image: canal/canal-server:v1.1.4
    container_name: canal-server
    ports:
      - "11111:11111"
    volumes:
      - ./canal-server-logs/:/home/admin/canal-server/logs/
      - ./canal-config/:/home/admin/canal-server/conf/
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: flink-test
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
